### ISSUE TITLE
Deploy ML models as python packages

### ISSUE THREAD

**Issue by thomashbrnrd** [dnum-mi/basegun-ml#11]
It would be better to distribute ML models or "modules" as packages so Basegun could install them easily without copy and pasting the code. include all files and data (models, tests images, thresholds,...)

- [x] Packaging ML models classification
- [x] Packaging ML models Measure
- [x] Create unit tests for classification
- [x] Create unit tests for measure
- [x] Launch unit tests
- [ ] Créer un script pour automatiser le déploiement (en stand-by selon type de déploiement)
- [x] Rediger la documentation
- [x] Publier le package sur Basegun-ML

**Comment by ClemGerard** [comment]
rédaction des tests unitaires.

En cours : Gestion de l'intégration des poids du modèle dans le package pour permettre leur modification de façon plus aisée.

**Comment by AurelienmartW** [comment]
Le packaging du modèle de classification est bien avancé.
La principale difficultée restante et le fait d'inclure des "package data" (fichiers non code tels que les poids du modèle ou des images tests)
En effet lors de la compilation du package ces fichiers ne sont pas conservés

**Comment by ClemGerard** [comment]
pas de déploiement sur Pypy donc pas besoin du script de déploiement pour l'instant

**Comment by ClemGerard** [comment]
Tests avec @thomashbrnrd pour confirmer que ça fonctionne.

**Comment by ClemGerard** [comment]
A tester by @thomashbrnrd
