### ISSUE TITLE
Dévelopement du module de détection d'armes d'alarmes

### ISSUE THREAD

**Issue by AurelienmartW** [dnum-mi/basegun-ml#6]
- [x] Implémenter PaddleOCR
- [x] Créer fonction de traitement de texte
- [x] Créer des règles de gestion pour la détection de modèle d'arme d'alarme
- [x] Validation des règles de gestion
- [x] Développer les règles de gestion associées
- [x] Creer une pipeline de traitement (preprocessing, ocr, post traitement, regles metiers)
- [x] Packaging du modèle
- [x] Evaluation de la pipeline globale de détection d'arme d'alarme sur le dataset de test
- [x] Validation des performances avec les experts métiers (31/07)

**Comment by leihuayi** [comment]
Utilisation de l'API d'OCR plutôt que Paddle en local sur le serveur ?

**Comment by leihuayi** [comment]
Si utilisation de PaddleOCR: attention au téléchargement potentiel de modèles lors du run. Voir un fix ici https://github.com/IA-Generative/ocr/commit/132b03c60fbcbc7a2d9076fb700e2349cd8b747d

**Comment by leihuayi** [comment]
@AurelienmartW investigue pour éviter le téléchargement des modèles lors du run. Il y a 3 modèles qui interviennent pour l'OCR qui sont fournis par défaut, mais si on veut Paddle propose une bibliothèque avec d'autres -> @AurelienmartW va tester des modèles issues de ces bibliothèques voir si on ne peut pas optimiser

**Comment by AurelienmartW** [comment]
Evaluation en cours de la pipeline globale.
On profite de l'évaluation sur le dataset de test de 500 images pour adapter les seuils d'IQA ainsi que les regles de gestion pour la detection d'arme d'alarme

**Comment by AurelienmartW** [comment]
Après évaluation des resultats de la pipeline de detection d'armes d'alarme on a pu adapter les regles de gestion.
Certains modèles d'armes ne presentent pas le nom de la marque il faut donc enlever cette règle.

Concernant les marquages PAK certains ont un marquage PA Knall ce qui veut dire la même chose, à inclure dans les règles de détection.

Dans les 2 cas de détection, on obtient 100% de précision, ainsi lorsqu'on indique qu'une arme est bien une arme d'alarme on est sûr à 100% (scénario prudent)

Les différences sont surtout au niveau du recall (combien d'armes d'alarme sont bien detectées/ l'ensemble des armes d'alarmes)

Le recall varie selon:

- La qualité de l'image
- le lisibilité (définie lors de la labellisation)
- le type de vue (globale ou rapprochée)
- le type de marquages (gravure, impression ...)

Une formalisation des résultats est en cours pour présenter les statisitques globales.

**Comment by AurelienmartW** [comment]
Arbitrage sur la pipeline de prétraitement réalisé avec les métiers
Ecrans en cours de définitions pour les cas:
- Photo mauvaise qualité
- Texte non détecté
